services:
  db:
    image: redis:latest
    ports:
      - "6379:6379"

  test-server-1:
    build:
      context: ./test_server
      dockerfile: Dockerfile
    container_name: test-server-1
    ports:
      - "8081:8081"
    environment:
      - PORT=8081

  test-server-2:
    build:
      context: ./test_server
      dockerfile: Dockerfile
    container_name: test-server-2
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - DELAY=200

  test-server-3:
    build:
      context: ./test_server
      dockerfile: Dockerfile
    container_name: test-server-3
    ports:
      - "8083:8083"
    environment:
      - PORT=8083