services:
  db:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - test-server-1
      - test-server-2
      - test-server-3

  test-server-1:
    build:
      context: ./test_server
      dockerfile: Dockerfile
    container_name: test-server-1
    expose:
      - "8081"
    environment:
      - PORT=8081

  test-server-2:
    build:
      context: ./test_server
      dockerfile: Dockerfile
    container_name: test-server-2
    expose:
      - "8082"
    environment:
      - PORT=8082
      - DELAY=200

  test-server-3:
    build:
      context: ./test_server
      dockerfile: Dockerfile
    container_name: test-server-3
    expose:
      - "8083"
    environment:
      - PORT=8083
