services:
  db:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - test-server-1
      - test-server-2
      - test-server-3
      - test-server-4
      - test-server-5

  test-server-1:
    build:
      context: ./test_server
      dockerfile: Dockerfile
    container_name: test-server-1
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DELAY=50

  test-server-2:
    build:
      context: ./test_server
      dockerfile: Dockerfile
    container_name: test-server-2
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - DELAY=100

  test-server-3:
    build:
      context: ./test_server
      dockerfile: Dockerfile
    container_name: test-server-3
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - DELAY=150

  test-server-4:
    build:
      context: ./test_server
      dockerfile: Dockerfile
    container_name: test-server-4
    ports:
      - "8084:8084"
    environment:
      - PORT=8084
      - DELAY=200

  test-server-5:
    build:
      context: ./test_server
      dockerfile: Dockerfile
    container_name: test-server-5
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
      - DELAY=300
