services:
  db:
    image: redis:latest
    ports:
      - "6379:6379"

  test_server_1:
    build:
      context: ./test_server
      dockerfile: Dockerfile
    container_name: test_server_1
    ports:
      - "8081:8081"
    environment:
      - PORT=8081

  test_server_2:
    build:
      context: ./test_server
      dockerfile: Dockerfile
    container_name: test_server_2
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - DELAY=200

  test_server_3:
    build:
      context: ./test_server
      dockerfile: Dockerfile
    container_name: test_server_3
    ports:
      - "8083:8083"
    environment:
      - PORT=8083